# stylish-haskell configuration file
# ==================================

# The stylish-haskell tool is mainly configured by specifying steps. These steps
# are a list, so they have an order, and one specific step may appear more than
# once (if needed). Each file is processed by these steps in the given order.
steps:
  - imports:
      align: global
      list_align: after_alias
      long_list_align: inline
      list_padding: 4
      separate_lists: true
  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true
  - tabs:
      spaces: 4
  - trailing_whitespace: {}
columns: 80
language_extensions:
  - OverloadedStrings
